import Papyrus.IR.Align
import Papyrus.IR.AddressSpace
import Papyrus.IR.TypeID
import Papyrus.IR.TypeRef
import Papyrus.IR.TypeRefs
import Papyrus.IR.TypeBases
import Papyrus.IR.Type
import Papyrus.IR.Types
import Papyrus.IR.ValueKind
import Papyrus.IR.ValueRef
import Papyrus.IR.ConstantRef
import Papyrus.IR.ConstantRefs
import Papyrus.IR.InstructionKind
import Papyrus.IR.InstructionModifiers
import Papyrus.IR.InstructionRef
import Papyrus.IR.InstructionRefs
import Papyrus.IR.BasicBlockRef
import Papyrus.IR.GlobalModifiers
import Papyrus.IR.FunctionRef
import Papyrus.IR.GlobalVariableRef
import Papyrus.IR.ModuleRef
