import Papyrus.IR.TypeID
import Papyrus.IR.TypeRef
import Papyrus.IR.TypeRefs
import Papyrus.IR.ValueRef
import Papyrus.IR.ConstantRefs
import Papyrus.IR.InstructionRefs
import Papyrus.IR.BasicBlockRef
import Papyrus.IR.FunctionRef
import Papyrus.IR.GlobalVariableRef
import Papyrus.IR.ModuleRef
import Papyrus.IR.AddressSpace
