name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell || 'sh' }}
    strategy:
      matrix:
        include:
        - name: Linux
          os: ubuntu-latest
        - name: macOS
          os: macos-latest
        - name: Windows
          os: windows-latest
          shell: msys2 {0}
      # complete all jobs
      fail-fast: false
    steps:
    - name: Install MSYS2
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        install: curl unzip make mingw-w64-x86_64-llvm mingw-w64-x86_64-gcc diffutils
    - name: Install Elan
      if: matrix.os != 'macOS-latest'
      run: |
        curl -sSL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh > elan-init.sh
        chmod +x elan-init.sh
        ./elan-init.sh -y
        dirname $(which elan) >> $GITHUB_PATH
    - name: Install Elan
      if: matrix.os == 'macOS-latest'
      run: brew install elan
    - name: Install LLVM
      if: matrix.os == 'macOS-latest'
      run: brew install llvm@12
    - name: Install LLVM
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libllvm12 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build C Lib
      run: make c
    - name: Build Lean Lib
      run: make lib
    - name: Build Lean Plugin
      run: make plugin
    - name: Test
      run: make test

